### ISSUE TITLE
对部分csb文件无法转换

### ISSUE THREAD

**Issue by ZzzzHhhhao** [lyzz0612/csb2csd#16]
我对test文件夹下的csb进行测试，可以正确转换，然而在对我想要的csb文件进行转换时发生了错误

```
D:\csb2csd\csb2csd-master>python convert.py csd csd
Traceback (most recent call last):
  File "D:\csb2csd\csb2csd-master\convert.py", line 477, in <module>
    main()
  File "D:\csb2csd\csb2csd-master\convert.py", line 468, in main
    dealWithCsbFile(p,outfile)
  File "D:\csb2csd\csb2csd-master\convert.py", line 446, in dealWithCsbFile
    startConvert(csbPath, csparsebinary, targetPath)
  File "D:\csb2csd\csb2csd-master\convert.py", line 433, in startConvert
    writeAction(csparsebinary.Action())
  File "D:\csb2csd\csb2csd-master\convert.py", line 192, in writeAction
    duration = actionData.Duration()
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Duration'
```

**Comment by l5276261** [comment]
你这是cocosstudio 2.x发布的csb文件吧
