### ISSUE TITLE
AttributeError: 'TextAtlasOptions' object has no attribute 'startCharMap'

### ISSUE THREAD

**Issue by JasonMrQ** [lyzz0612/csb2csd#3]
Traceback (most recent call last):
  File "convert.py", line 437, in <module>
    main()
  File "convert.py", line 434, in main
    walk_dir(sys.argv[2],CSD_TARGET_ROOT)
  File "convert.py", line 426, in walk_dir
    dealWithCsbFile(dir + pathname + '/' + name , targetDir)
  File "convert.py", line 403, in dealWithCsbFile
    startConvert(csbPath, csparsebinary,targetDir)
  File "convert.py", line 394, in startConvert
    recursionConvertTree(nodeTree)
  File "convert.py", line 376, in recursionConvertTree
    recursionConvertTree(child, level + 1)
  File "convert.py", line 369, in recursionConvertTree
    writeOption(nodeTree, baseTab)
  File "convert.py", line 363, in writeOption
    writeOptionHeader(realOption, widgetOption, className, tab)
  File "convert.py", line 286, in writeOptionHeader
    text = text + getHeaderOption(optionData, ruleOption[0], ruleOption[1], ruleOption[2], ruleOption[3])
  File "convert.py", line 241, in getHeaderOption
    func = getattr(parentValue, path)
AttributeError: 'TextAtlasOptions' object has no attribute 'startCharMap'

**Comment by JasonMrQ** [comment]
[](url)

**Comment by lyzz0612** [comment]
thanks for feedback! can you provide your csb file here or a link, I want to reproduce it. thank you.

**Comment by JasonMrQ** [comment]
Hi, I found an error in the 'header_ruler.json' due to the case of the first letter
Before:
"TextAtlas":[
	....
		["StartChar", "startCharMap", "", ""]
	],

After:
"TextAtlas":[
	....
		["StartChar", "StartCharMap", "", ""]
	],

**Comment by lyzz0612** [comment]
yes, you are right! Fixed! thank you.
